const styles = {
  container: {
    minHeight: "100vh",
    backgroundColor: "#f8fafc",
    padding: "clamp(16px, 3vw, 24px)",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  },
  header: {
    marginBottom: "clamp(24px, 4vw, 32px)",
  },
  title: {
    fontSize: "clamp(24px, 4vw, 28px)",
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: "8px",
  },
  subtitle: {
    fontSize: "clamp(14px, 2vw, 16px)",
    color: "#64748b",
  },
  controls: {
    marginBottom: "clamp(16px, 3vw, 24px)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  controlsRow: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
  },
  leftControls: {
    display: "flex",
    gap: "12px",
    alignItems: "center",
    flex: "1",
  },
  searchContainer: {
    position: "relative",
    flex: "1",
    maxWidth: "clamp(300px, 50vw, 400px)",
  },
  searchInput: {
    width: "100%",
    padding: "12px 12px 12px 40px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    outline: "none",
    transition: "all 0.2s",
    backgroundColor: "white",
  },
  searchIcon: {
    position: "absolute",
    left: "12px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#9ca3af",
    width: "16px",
    height: "16px",
  },
  filterButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 16px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    backgroundColor: "white",
    cursor: "pointer",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    color: "#374151",
    transition: "all 0.2s",
  },
  sortSelect: {
    padding: "12px 32px 12px 16px",
    border: "1px solid #d1d5db",
    borderRadius: "8px",
    backgroundColor: "white",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    color: "#374151",
    outline: "none",
    cursor: "pointer",
    appearance: "none",
    backgroundImage:
      'url("data:image/svg+xml,%3csvg xmlns=\'http://www.w3.org/2000/svg\' fill=\'none\' viewBox=\'0 0 20 20\'%3e%3cpath stroke=\'%236b7280\' stroke-linecap=\'round\' stroke-linejoin=\'round\' stroke-width=\'1.5\' d=\'M6 8l4 4 4-4\'/%3e%3c/svg%3e")',
    backgroundPosition: "right 12px center",
    backgroundRepeat: "no-repeat",
    backgroundSize: "16px",
  },
  exportButton: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    padding: "12px 20px",
    backgroundColor: "#16a34a",
    color: "white",
    border: "none",
    borderRadius: "8px",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    fontWeight: "500",
    cursor: "pointer",
    transition: "all 0.2s",
  },
  tableContainer: {
    backgroundColor: "white",
    borderRadius: "12px",
    boxShadow: "0 1px 3px rgba(0, 0, 0, 0.1)",
    border: "1px solid #e2e8f0",
    overflow: "hidden",
    overflowX: "auto",
  },
  tableHeader: {
    display: "grid",
    gridTemplateColumns:
      "minmax(100px, 120px) minmax(200px, 2fr) minmax(80px, 1fr) minmax(60px, 80px) minmax(120px, 140px) minmax(100px, 120px) minmax(60px, 80px)",
    gap: "16px",
    padding: "16px",
    backgroundColor: "#f8fafc",
    borderBottom: "1px solid #e2e8f0",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    fontWeight: "600",
    color: "#475569",
    minWidth: "800px",
  },
  tableBody: {
    borderTop: "1px solid #e2e8f0",
    minWidth: "800px",
  },
  tableRow: {
    display: "grid",
    gridTemplateColumns:
      "minmax(100px, 120px) minmax(200px, 2fr) minmax(80px, 1fr) minmax(60px, 80px) minmax(120px, 140px) minmax(100px, 120px) minmax(60px, 80px)",
    gap: "16px",
    padding: "16px",
    alignItems: "center",
    borderBottom: "1px solid #f1f5f9",
    transition: "all 0.2s",
  },
  patientId: {
    fontSize: "clamp(12px, 1.8vw, 14px)",
    fontWeight: "600",
    color: "#1e293b",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  patientInfo: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
  },
  patientDetails: {
    display: "flex",
    flexDirection: "column",
    gap: "4px",
    minWidth: 0,
  },
  patientName: {
    fontSize: "clamp(12px, 1.8vw, 14px)",
    fontWeight: "600",
    color: "#1e293b",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  appointmentType: {
    fontSize: "clamp(10px, 1.5vw, 12px)",
    color: "#64748b",
    fontWeight: "500",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  statusBadgeGreen: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: "20px",
    fontSize: "clamp(10px, 1.5vw, 12px)",
    fontWeight: "500",
    backgroundColor: "#dcfce7",
    color: "#166534",
  },
  statusBadgeOrange: {
    display: "inline-flex",
    alignItems: "center",
    padding: "4px 8px",
    borderRadius: "20px",
    fontSize: "clamp(10px, 1.5vw, 12px)",
    fontWeight: "500",
    backgroundColor: "#fed7aa",
    color: "#9a3412",
  },
  tableCell: {
    fontSize: "clamp(12px, 1.8vw, 14px)",
    color: "#64748b",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  actionButton: {
    padding: "8px",
    border: "none",
    backgroundColor: "transparent",
    cursor: "pointer",
    borderRadius: "4px",
    transition: "all 0.2s",
  },
  pagination: {
    marginTop: "clamp(16px, 3vw, 24px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    flexWrap: "wrap",
    gap: "16px",
  },
  paginationInfo: {
    fontSize: "clamp(12px, 1.8vw, 14px)",
    color: "#64748b",
  },
  paginationControls: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  paginationButton: {
    padding: "8px 12px",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    border: "none",
    backgroundColor: "transparent",
    color: "#64748b",
    cursor: "pointer",
    borderRadius: "6px",
    transition: "all 0.2s",
  },
  paginationButtonActive: {
    padding: "8px 12px",
    fontSize: "clamp(12px, 1.8vw, 14px)",
    border: "none",
    backgroundColor: "#3b82f6",
    color: "white",
    cursor: "pointer",
    borderRadius: "6px",
    fontWeight: "500",
  },
  filterModalContent: {
    display: "flex",
    flexDirection: "column",
    gap: "16px",
    padding: "16px",
  },
  filterField: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  filterLabel: {
    fontSize: "14px",
    fontWeight: "500",
    color: "#374151",
  },
  prescriptionSection: {
    marginBottom: "24px",
    paddingBottom: "16px",
    borderBottom: "1px solid #e5e7eb",
  },
  sectionTitle: {
    marginBottom: "16px",
    color: "#1f2937",
    fontSize: "18px",
    fontWeight: "600",
  },
  subSection: {
    marginBottom: "16px",
  },
  subSectionTitle: {
    marginBottom: "12px",
    color: "#374151",
    fontSize: "16px",
    fontWeight: "500",
  },
  infoGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(250px, 1fr))",
    gap: "16px",
    marginBottom: "16px",
  },
  infoItem: {
    display: "flex",
    justifyContent: "space-between",
    padding: "8px 12px",
    backgroundColor: "#f9fafb",
    borderRadius: "6px",
    fontSize: "14px",
    color: "#4b5563",
  },
  loadingMessage: {
    textAlign: "center",
    padding: "20px",
    color: "#6b7280",
    fontSize: "14px",
  },
  noDataMessage: {
    padding: "12px",
    backgroundColor: "#f3f4f6",
    borderRadius: "6px",
    color: "#6b7280",
    textAlign: "center",
    fontSize: "14px",
    marginTop: "8px",
  },

  modalHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "16px",
    paddingBottom: "12px",
    borderBottom: "1px solid #e5e7eb",
  },
  modalTitle: {
    fontSize: "20px",
    fontWeight: "600",
    color: "#1f2937",
    margin: 0,
  },
  modalCloseButton: {
    background: "none",
    border: "none",
    cursor: "pointer",
    fontSize: "18px",
    color: "#6b7280",
  },
  medicineTable: {
    marginTop: "16px",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
  },
  testTable: {
    marginTop: "16px",
    border: "1px solid #e5e7eb",
    borderRadius: "6px",
  },
  tableHeaderCell: {
    backgroundColor: "#f9fafb",
    fontWeight: "600",
    color: "#374151",
  },
  tableRowCell: {
    borderBottom: "1px solid #e5e7eb",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    marginTop: "24px",
    paddingTop: "16px",
    borderTop: "1px solid #e5e7eb",
  },
 
  closeButton: {
    padding: "8px 16px",
    backgroundColor: "#3b82f6",
    color: "white",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    fontWeight: "500",
    transition: "all 0.2s",
    "&:hover": {
      backgroundColor: "#2563eb",
    },
  },
};

export default styles;